### ISSUE TITLE
Is it detected now?

### ISSUE THREAD

**Issue by DrKelapa** [RatPoison-dev/RatPoison#782]
I heard valve have taken down this cheat 
Here's the link:
https://www.dexerto.com/csgo/valve-finally-cracking-down-on-one-of-csgos-most-common-cheats-1574686/

https://www.reddit.com/r/csgo/comments/nczfb7/one_of_the_most_popular_csgo_cheats_just_got_hit/

https://www.talkesport.com/news/csgo-vac-wave-wipes-cheaters-with-new-detections/

**Comment by 9191929992** [comment]
No, this is all bs. It's not detected.

**Comment by 9191929992** [comment]
Close issue tnx

**Comment by sotakoira** [comment]
I'll tell you how it started:

The original troll post was mentioned on new rattin server by Gytiss asking if it's real.
We decided to play along it. https://i.imgur.com/y7RGqRM.png

Legacy and Gytiss made some less or more convincing threads, one with updated VAC - https://i.imgur.com/9Uf7sa8.png, other following the r/ratpoison meme - https://i.imgur.com/ywDOXvd.png, everything died due to Mars or any other csgohacks mod deleting fake posts.

At some point an idea sparkled to elevate this into legit player subs like r/csgo or r/globaloffensive - https://i.imgur.com/HfeAI7Z.png

Post died on 700 upvotes - https://www.reddit.com/r/GlobalOffensive/comments/nczqln/one_of_the_most_popular_csgo_cheats_just_got_hit/ but later started being reposted:

https://twitter.com/geometric/status/1393588979090563078
https://www.dexerto.com/csgo/valve-finally-cracking-down-on-one-of-csgos-most-common-cheats-1574686/
https://www.talkesport.com/news/csgo-vac-wave-wipes-cheaters-with-new-detections/
https://afkgaming.com/articles/csgo/News/7958-valve-hammers-popular-csgo-cheat-with-full-vac-detection-bans-several-hackers
https://i.imgur.com/SDg6SM4.png https://i.imgur.com/GrIpq5B.png https://i.imgur.com/qR0aDAw.png https://i.imgur.com/GvN2fpX.png

Discord convo from those posts - https://i.imgur.com/WrUE30s.png https://i.imgur.com/mNemuYu.png (legacy got banned so his part is not here)
"Woke up to all of my accounts being VAC banned" - https://www.reddit.com/r/Csgohacks/comments/ncxf4o/ratpoison_users_read_this_very_important/gy7hepb/ - this is actually me, very convincing person shitposting without providing any proof

My take: I find it hilarious esport journalists report on anything they see without fact-checking. There's no proof anybody got banned, the only official detection status will be archived RatPoison repository and everyone ping in #announcements by either Ratto or Spravedlivo. 

My real take: lmao gottem https://i.imgur.com/e4lM9AU.png

**Comment by SPRAVEDLIVO** [comment]
i confirm man's above words

**Comment by matt1tk** [comment]
I as well

**Comment by DrKelapa** [comment]
Thank you for the information mate gonna close this issue rn

**Comment by HyderTheNN** [comment]
sex

**Comment by siautalius** [comment]
i didnt deserve to be called a colossal fuckhead, bad troll. please unban plz

**Comment by HyderTheNN** [comment]
> i didnt deserve to be called a colossal fuckhead, bad troll. please unban plz

fuck off homosex

**Comment by siautalius** [comment]
nn mad f12

**Comment by Firestarter1997** [comment]
But you all say its not detected but i was banned from using rat posion

![csgo account 4](https://user-images.githubusercontent.com/87560159/126027970-7672d558-4b11-4e4e-9398-b9af5c13cf98.PNG)

**Comment by hac41b1** [comment]
This is all bs. My accounts got banned. I can show you the proof.  These guys are just talking bs.

**Comment by sotakoira** [comment]
you are bs, dates here are 17 may, detection was 26 may
nine days after.
